### ISSUE TITLE
2.9.7 - Problems escalating

### ISSUE THREAD

**Issue by andrepetinga** [pluginsGLPI/escalade#218]
Hello.
1. When If I make several escalations, the history is not showned correctly.

For example: Created a ticket and the Group assigned was "CONTACT CENTER DSI"

![image](https://github.com/user-attachments/assets/86dab1f4-17cc-447c-8e87-1c504878adad)

Then escalate (using escalate button) to UARS and the visual history doesn't show any previous group:

![image](https://github.com/user-attachments/assets/0a15e7f7-8b6e-46ab-b35a-f292a8d29492)

Then escalate (using escalate button) to UAS and it only shows the previous group:

![image](https://github.com/user-attachments/assets/7e058d9a-6ecd-48ad-9aea-3fe803b0c903)

**LOGS:**

[2024-07-15 11:13:47] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "assign" in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1680                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1610                            Plugin::doHook()
  src/Ticket.php:2440                                CommonDBTM->update()
  src/CommonITILActor.php:434                        Ticket->updateDateMod()
  src/Group_Ticket.php:66                            CommonITILActor->post_addItem()
  src/CommonDBTM.php:1343                            Group_Ticket->post_addItem()
  src/CommonITILObject.php:8757                      CommonDBTM->add()
  src/CommonITILObject.php:2868                      CommonITILObject->updateActors()
  src/Ticket.php:2225                                CommonITILObject->post_addItem()
  src/CommonDBTM.php:1343                            Ticket->post_addItem()
  front/ticket.form.php:80                           CommonDBTM->add()
  public/index.php:82                                require()

[2024-07-15 11:13:47] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1680                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1610                            Plugin::doHook()
  src/Ticket.php:2440                                CommonDBTM->update()
  src/CommonITILActor.php:434                        Ticket->updateDateMod()
  src/Group_Ticket.php:66                            CommonITILActor->post_addItem()
  src/CommonDBTM.php:1343                            Group_Ticket->post_addItem()
  src/CommonITILObject.php:8757                      CommonDBTM->add()
  src/CommonITILObject.php:2868                      CommonITILObject->updateActors()
  src/Ticket.php:2225                                CommonITILObject->post_addItem()
  src/CommonDBTM.php:1343                            Ticket->post_addItem()
  front/ticket.form.php:80                           CommonDBTM->add()
  public/index.php:82                                require()

2. Another problem, is when we use the arrow icon to escalate.

![image](https://github.com/user-attachments/assets/36a4a192-138f-4589-8b43-c5112c27ce7b)

It only shows a blank page and checking the LOG:

[2024-07-15 11:20:22] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "ticket_details" in .../glpi/marketplace/escalade/inc/ticket.class.php at line 519
  Backtrace :
  marketplace/escalade/front/climb_group.php:42      PluginEscaladeTicket::climb_group()
  public/index.php:82                                require()

[2024-07-15 11:20:22] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Unsupported operand types: null + array in .../glpi/marketplace/escalade/inc/ticket.class.php at line 524
  Backtrace :
  marketplace/escalade/front/climb_group.php:42      PluginEscaladeTicket::climb_group()
  public/index.php:82                                require()

3. Another thing: If I escalate writing the group name, the "yellow task box" is not showned on the ticket history:

![image](https://github.com/user-attachments/assets/2d65708d-7b1d-4592-9b1b-2a531dbafff7)

Only shows history text, not the "yellow task box":

![image](https://github.com/user-attachments/assets/fe669c69-c854-4044-a27f-6af2d5355265)

**Comment by stonebuzz** [comment]
this should fix this issue (i hope)

https://github.com/pluginsGLPI/escalade/pull/212

**Comment by andrepetinga** [comment]
Hello @stonebuzz.
Today I updated to 2.9.8 version, and then apllied 2 fixes: #219 and #212.
Made new tests today and regarding my last post:

**SAME RESULT** ->**Problem 1 is confirmed** - Escalation history is not working properly. For example, it only shows up when we escalate using Escalate button. If we search for the group, the previous is not added to history.

**SAME RESULT** -> **Problem 3 is confirmed** - The yellow private task mentioning the escalade option it's only being created when we escalate using Escalate button. Not using the search textbox or using "up arrow" (escalade history).

**NEW RESULT** -> Found the errors mentioned on the first post when: ticket is created (we have a rule to assign a group).

Meaning -> Doing these actions: **making a solution, rejecting a solution, using the "associate myself" button no longer writes those errors on the logs**.

Errors are:

```
[2024-07-22 12:03:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "assign" in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1713                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1616                            Plugin::doHook()
  src/CommonITILObject.php:8712                      CommonDBTM->update()
  src/CommonITILObject.php:2868                      CommonITILObject->updateActors()
  src/Ticket.php:2225                                CommonITILObject->post_addItem()
  src/CommonDBTM.php:1349                            Ticket->post_addItem()
  src/MailCollector.php:897                          CommonDBTM->add()
  src/MailCollector.php:1923                         MailCollector->collect()
  src/CronTask.php:1027                              MailCollector::cronMailgate()
  front/cron.php:87                                  CronTask::launch()

[2024-07-22 12:03:05] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1713                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1616                            Plugin::doHook()
  src/CommonITILObject.php:8712                      CommonDBTM->update()
  src/CommonITILObject.php:2868                      CommonITILObject->updateActors()
  src/Ticket.php:2225                                CommonITILObject->post_addItem()
  src/CommonDBTM.php:1349                            Ticket->post_addItem()
  src/MailCollector.php:897                          CommonDBTM->add()
  src/MailCollector.php:1923                         MailCollector->collect()
  src/CronTask.php:1027                              MailCollector::cronMailgate()
  front/cron.php:87                                  CronTask::launch()
```
But using the "associate myself" button is writting a new error, since I applied the #219 patch.


**SAME RESULT** -> **New problem found**: If we have a requester or observer  with an email (external user), **the observer email will be deleted if escalade using the Escalate button or the "up arrow" (escalade history)**. The observer will stay if we escalade searching for the group.
And we can see this on the LOGS:

```
2024-07-22 12:07:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in .../glpi/src/CommonITILObject.php at line 9884
Backtrace :
src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
marketplace/escalade/front/ticket.form.php:70      CommonDBTM->update()
public/index.php:82                                require()
```

**Comment by ftoledo** [comment]
Hi @andrepetinga  What version of glpi are you using?

**Comment by andrepetinga** [comment]
> Hi @andrepetinga What version of glpi are you using?

10.0.16

**Comment by stonebuzz** [comment]
Hi @andrepetinga 

_SAME RESULT -> Problem 3 is confirmed - The yellow private task mentioning the escalade option it's only being created when we escalate using Escalate button. Not using the search textbox or using "up arrow" (escalade history)._

Should be fixed by https://github.com/pluginsGLPI/escalade/pull/230

**Comment by stonebuzz** [comment]
Hi @andrepetinga 

_NEW RESULT -> No errors found when: ticket is created (we have a rule to assign a group), making a solution, rejecting a solution, using the "associate myself" button no longer writes those errors on the logs._

Should be fixed by https://github.com/pluginsGLPI/escalade/pull/231

**Comment by stonebuzz** [comment]
Hi @andrepetinga @ftoledo 

can you retry by using "main" branch ?

after testing, the recent PR corrected the problem

**Comment by andrepetinga** [comment]
> Hi @andrepetinga
> 
> _SAME RESULT -> Problem 3 is confirmed - The yellow private task mentioning the escalade option it's only being created when we escalate using Escalate button. Not using the search textbox or using "up arrow" (escalade history)._
> 
> Should be fixed by #230

Hi @stonebuzz.
Sorry for the delay...

Just picked up my installed 2.9.8 version and only applied the #230.
What I did was to manually change the "'_plugin_escalade_no_history' => true" to "'_plugin_escalade_no_history' => false"

Testing:

When using the Escalade Button -> Still OK
When using the Arrow from the History -> Now it's OK
When searching the a group -> Still NOT OK!

![image](https://github.com/user-attachments/assets/31551c32-3619-4840-8569-481e2d8b0284)

As you can see in the print, the Group "UGSI" was added at 14:43, and no Private task

**Comment by stonebuzz** [comment]
Hi @andrepetinga

can you retry with main branch (not 2.9.8 + one patch)

**Comment by andrepetinga** [comment]
> Hi @stonebuzz. Sorry for the delay...
> 
> Just picked up my installed 2.9.8 version and only applied the #230. What I did was to manually change the "'_plugin_escalade_no_history' => true" to "'_plugin_escalade_no_history' => false"
> 
> Testing:

Hi @stonebuzz.

Continued with my installed 2.9.8 version (now also with #230 correction) and only applied the #231.
What I did was to manually change the "$tickets_id = $item->input['id'];" to "$tickets_id = $item->input['id'] ?? $item->fields['id'];"

Testing:

**No error on the logs when using the "associate myself" button.**

**Comment by andrepetinga** [comment]
> Hi @andrepetinga
> 
> can you retry with main branch (not 2.9.8 + one patch)

Yes, that was my plan :)

And yes, using the main branch:

When using the Escalade Button -> OK!
When using the Arrow from the History -> OK!
When searching the a group -> OK!

**Comment by andrepetinga** [comment]
> Hello @stonebuzz. Today I updated to 2.9.8 version, and then apllied 2 fixes: #219 and #212. Made new tests today and regarding my last post:
> 
> **SAME RESULT** ->**Problem 1 is confirmed** - Escalation history is not working properly. For example, it only shows up when we escalate using Escalate button. If we search for the group, the previous is not added to history.
> 
> **SAME RESULT** -> **Problem 3 is confirmed** - The yellow private task mentioning the escalade option it's only being created when we escalate using Escalate button. Not using the search textbox or using "up arrow" (escalade history).
> 
> **NEW RESULT** -> No errors found when: ticket is created (we have a rule to assign a group), making a solution, rejecting a solution, using the "associate myself" button no longer writes those errors on the logs.
> 
> But using the "associate myself" button is writting a new error, since I applied the #219 patch.
> 
> **SAME RESULT** -> **New problem found**: If we have a requester or observer with an email (external user), **the observer email will be deleted if escalade using the Escalate button or the "up arrow" (escalade history)**. The observer will stay if we escalade searching for the group. And we can see this on the LOGS:
> 
> ```
> 2024-07-22 12:07:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in .../glpi/src/CommonITILObject.php at line 9884
> Backtrace :
> src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
> src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
> marketplace/escalade/front/ticket.form.php:70      CommonDBTM->update()
> public/index.php:82                                require()
> ```

Hello @stonebuzz.

So, after installing the main branch of 2.9.8 (no patches added), I repeated all my tests and:

**NEW RESULT ->Problem 1 no longer exists** - Escalation history is now working properly.

**NEW RESULT -> Problem 3 no longer exists** - The yellow private task mentioning the escalade option it's being created.

**NEW RESULT -> Now, using the  "associate myself" button no longer raises an error on the log.**

**SAME RESULT** -> **New problem found**: If we have a requester or observer with an email (external user), **the observer email will be deleted if escalade using the Escalate button or the "up arrow" (escalade history)**. The observer will stay if we escalade searching for the group.

And we can see this on the LOGS:

Using the "up arrow" (escalade history):
```
[2024-09-04 15:24:03] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in …/glpi/src/CommonITILObject.php at line 9884
  Backtrace :
  src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
  src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
  marketplace/escalade/inc/ticket.class.php:509      CommonDBTM->update()
  marketplace/escalade/front/climb_group.php:40      PluginEscaladeTicket::climb_group()
  public/index.php:82                                require()
```

Using the Escalate button:

```
[2024-09-04 15:18:30] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in …/glpi/src/CommonITILObject.php at line 9884
  Backtrace :
  src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
  src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
  marketplace/escalade/front/ticket.form.php:70      CommonDBTM->update()
  public/index.php:82                                require()
```


Almost there!!! :)

**Comment by stonebuzz** [comment]
Can you (please) open a new issue ?

**Comment by andrepetinga** [comment]
Just created the new issue #241

**Comment by ftoledo** [comment]
> Hi @andrepetinga @ftoledo
> 
> can you retry by using "main" branch ?
> 
> after testing, the recent PR corrected the problem

hi @stonebuzz  i can confirm that main branch has solved the issue.
thanks!

**Comment by stonebuzz** [comment]
in view of the recent progress and feedback from the community, I'm closing this issue.

release coming soon
